### ISSUE TITLE
Bucket credentials NO KMS

### ISSUE THREAD

**Issue by ram-bo-arm** [stevegal/jenkins-aws-bucket-credentials#1]
Do you have plan to add a support for retrieval of credentials from Amazon S3 bucket stored using S3 internal encryption ?

**Comment by stevegal** [comment]
Currently only jms encryption is supported. Do you mean http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html or http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html
I'm sure I can add either as an option/variant. Let me know which you want first and I'll add it in an upcoming release.

**Comment by stevegal** [comment]
sorry kms not jms

**Comment by ram-bo-arm** [comment]
I mean the first one - SSE-S3

**Comment by stevegal** [comment]
Okay. I'll make sure I work on that when I have some time.

**Comment by stevegal** [comment]
I've release 0.2.0. If you leave out the kms settings, it'll just use the result from the s3 bucket directly. This should work with server side encryption on the s3 bucket.

Let me know if it works

**Comment by stevegal** [comment]
@ram-bo-arm

**Comment by ram-bo-arm** [comment]
If I understood correctly , leaving out the KMS setting :EncryptionContextKey , EncryptionValue might be problematic and cause a comparability issue.
It is valid KMS configuration to work with KMS without those optional settings.
Why not set the the  SSE-S3 explicitly in the configuration ?

**Comment by stevegal** [comment]
I was attempting something quick for you and missed the side effect. I'll correct and add in configuration. It'll be something like use `kms` as the SSE-S3 cannot be enforced by the get on the object. In the interim, can you confirm that s3 SSE is doable in this approach? I'll clean up the trigger after. Can I ask you to comment in the [jenkins fork](https://github.com/jenkinsci/aws-bucket-credentials-plugin) in future please? (and keep the issues/requests coming!)

**Comment by ram-bo-arm** [comment]
I will soon let you know about the s3 SSE status.
I cant add comments on the fork since it has no "Issues" tab

**Comment by ram-bo-arm** [comment]
I am sorry but I couldn't add this comment in the fork.
When working in SSE mode and taking off the values of  EncryptionContextKey , EncryptionValue , I keep getting this error -

com.amazonaws.services.kms.model.AWSKMSException: Invalid EncryptionContext (Service: AWSKMS; Status Code: 400; Error Code: ValidationException; Request ID: af6614a4-ad24-11e7-a7bc-df7a0f406304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:3031)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:3007)
	at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:811)
	at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:787)
	at

**Comment by stevegal** [comment]
No problem and thanks for testing for me! I’ll add a flag to control KMS or just get. For the sake of serialisation it’ll be a “don’t use kms” flag so that the default of false will preserve functionality. I’ll add this ASAP.

**Comment by stevegal** [comment]
sorry about the bad re-direct to the issues bit in github. No idea why they don't allow comments there! Keep the comments and issues coming here in that case. I've released 0.2.2 with the added flag. Again @ram-bo-arm can you please test this for me?

if it doesn't appear in the official release you can find the hpi [here](https://repo.jenkins-ci.org/releases/uk/co/stevegal/aws-bucket-credentials/)

**Comment by ram-bo-arm** [comment]
I am initializing the object during the groovy init phase like that :

awsBucketCredential = new AwsBucketCredentialsImpl(CredentialsScope.GLOBAL,
                                                credentialId,
                                                region,
                                                bucketName,
                                                bucketPath,
                                                username,
                                                s3Proxy,
                                                description,
                                                null,
                                                proxyHost,
                                                proxyPort)

Then adding it to the certificate store:

store.addCredentials(domain, awsBucketCredential)

When looking at the UI, the "Kms Encryption Not Required" is NOT set.
As a result the plugin tries to decrypt the password and it doesn't "Avoid KMS"
Am I doing something wrong ?

**Comment by ram-bo-arm** [comment]
Also when trying to set the "Not KMS " on and update the certificate manually thru the UI I get back blank page : credentials/store/system/domain/_/credential/aws-s3-kms-github/updateSubmit
and the certificate is not being updated with the right value.

**Comment by stevegal** [comment]
I’ve got a jelly issue there. Set it and don’t update. It’ll work. I could either have the section box always there and have the check box show correctly or the disappearing check. Judging by your confusion I made the wrong choice :(. However, the functionality should work ignoring the ui issue.

**Comment by ram-bo-arm** [comment]
I can confirm it does work :-)
Many thanks for your help and support

**Comment by stevegal** [comment]
I’ll close the issue then. Thanks for your patience!
