### ISSUE TITLE
crash when running on slave

### ISSUE THREAD

**Issue by ram-bo-arm** [stevegal/jenkins-aws-bucket-credentials#2]
The plugin works on the master node without any problem
However  when running on a slave node it crashed with the following dump (partially)
FATAL: null
java.lang.NullPointerException
	at jenkins.security.ConfidentialStore.get(ConfidentialStore.java:67)
	at jenkins.security.ConfidentialKey.load(ConfidentialKey.java:47)
	at jenkins.security.CryptoConfidentialKey.getKey(CryptoConfidentialKey.java:41)
	at jenkins.security.CryptoConfidentialKey.decrypt(CryptoConfidentialKey.java:134)
	at hudson.util.HistoricalSecrets.decrypt(HistoricalSecrets.java:49)
	at hudson.util.Secret.decrypt(Secret.java:207)
	at hudson.util.Secret.fromString(Secret.java:239)
	at uk.co.stevegal.jenkins.plugins.awsbucketcredentials.AwsBucketCredentialsImpl.getPassword(AwsBucketCredentialsImpl.java:103)

To my understanding calling "return Secret.fromString(rawString);" from getPassword might be problematic since the slave has no credentialStore.

I have a forked repo which obtains the password in the constructor and store it as a var .
(This phase is running only on the master)
In the getPassword function I return the var I saved before.
This behavior is similar to the UsernamePasswordCredentials implementation  where the password is stored during the construction stage.

**Comment by stevegal** [comment]
I was deliberately leaving the Secret decode as late as possible as I was being paranoid about leaving it in memory.

**Comment by stevegal** [comment]
just a quick look at the documentation... I found this "If you convinced yourself that this is the right thing to do, you can go to http://jenkins/configureSecurity and uncheck "Enable Slave → Master Access Control" option. This setting is remembered by $JENKINS_HOME/secrets/slave-to-master-security-kill-switch. The file should either contain true or false as the content (when the kill-switch is set to false, it means that Slave → Master Access Control is enabled). If you do not want this be configurable by administrator, you can make this file read-only for Jenkins." 

Does that help?

**Comment by stevegal** [comment]
I also wanted to leave the decrypt for use as I thought that would allow for password rotation in the bucket. I’m not sure of the lifespan for the objects. If I move to the constructor method, is it created per build?

**Comment by ram-bo-arm** [comment]
No ,its created once during Jenkins startup.

**Comment by stevegal** [comment]
Think I’ll need to figure out how CredentialsSnapshotTaker hooks into this. I presume I could take a snapshot of the current Secret. But I need to figure out how this works wrt lifecycle of credentials.

**Comment by stevegal** [comment]
@ram-bo-arm - I've confirmed that if you have the correct settings between master and slave this works. For this to work there must be great trust between master and slave so only use if you own the slave as well as the master (normal caveat there). Can you confirm?

**Comment by ram-bo-arm** [comment]
Can you further elaborate what are the correct settings ?

**Comment by stevegal** [comment]
If you go to "Manage Jenkins"->"Configure Global Security" there is a section at the bottom labelled "Plugin Management", make sure "Enable Slave->Master Access Control" is *off*

This is on Jenkins 2.7.3

**Comment by stevegal** [comment]
and this is how I tried it..
```
pipeline {
    agent { label 'your-slave-label-here' }
    stages{
        stage("cmd") {
            steps{
                withCredentials([usernamePassword(credentialsId: 'aws-bucket-credentials-id', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
  // available as an env variable, but will be masked if you try to print it out any which way
  sh 'echo $PASSWORD'
  // also available as a Groovy variable—note double quotes for string interpolation
  echo "$USERNAME"
}
            }
        }
    }
}
```

which outputs
```
Running on you-slave-id-here in /var/jenkins/workspace/slave-cmd
[Pipeline] {
[Pipeline] stage
[Pipeline] { (cmd)
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh
[slave-cmd] Running shell script
+ echo ****
****
[Pipeline] echo
****
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by stevegal** [comment]
@ram-bo-arm did you manage to get it running? can I close this issue?

**Comment by ram-bo-arm** [comment]
you can close ,I validated
